const shopActionTypes = {
    FETCH_COLLECTIONS_START: 'shop/FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS: 'shop/FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAIL: 'shop/FETCH_COLLECTIONS_FAIL',
    UPDATE_COLLECTIONS: 'shop/UPDATE_COLLECTIONS'
}

export default shopActionTypes;