export const types = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',

    TOGGLE_CART_HIDDEN: 'cart/TOGGLE_CART_HIDDEN',
    CLEAR_ITEM_FROM_CART: 'cart/CLEAR_ITEM_FROM_CART',
    ADD_ITEM: 'cart/ADD_ITEM',
    REMOVE_ITEM: 'cart/REMOVE_ITEM'
}
