export const types = {
    SET_CURRENT_USER: 'user/SET_CURRENT_USER',
    GOOGLE_SIGN_IN_START: 'user/GOOGLE_SIGN_IN_START',
    GOOGLE_SIGN_IN_SUCCESS: 'user/GOOGLE_SIGN_IN_SUCCESS',
    GOOGLE_SIGN_IN_FAIL: 'user/GOOGLE_SIGN_IN_FAIL',
    EMAIL_SIGN_IN_START: 'user/EMAIL_SIGN_IN_START',
    EMAIL_SIGN_IN_SUCCESS: 'user/EMAIL_SIGN_IN_SUCCESS',
    EMAIL_SIGN_IN_FAIL: 'user/EMAIL_SIGN_IN_FAIL',

    TOGGLE_CART_HIDDEN: 'cart/TOGGLE_CART_HIDDEN',
    CLEAR_ITEM_FROM_CART: 'cart/CLEAR_ITEM_FROM_CART',
    ADD_ITEM: 'cart/ADD_ITEM',
    REMOVE_ITEM: 'cart/REMOVE_ITEM'
}
